/*
 * GENERATED FILE - DO NOT EDIT.
 * Source: src/config/audio_runtime_profile.json
 * Generator: scripts/generate-audio-runtime-profile.py
 *
 * Selected Configuration values only; no media-clock offset is duplicated
 * here and no AUDIO runtime mechanism is activated by these constants.
 */

#ifndef PSTVNC_CONFIG_AUDIO_RUNTIME_PROFILE_GENERATED_H
#define PSTVNC_CONFIG_AUDIO_RUNTIME_PROFILE_GENERATED_H

#include <stdint.h>

#define PSTVNC_CONFIG_AUDIO_QUEUE_CAPACITY UINT32_C(524288)
#define PSTVNC_CONFIG_AUDIO_INITIAL_CREDIT_BYTES UINT32_C(524288)
#define PSTVNC_CONFIG_AUDIO_CREDIT_BATCH_BYTES UINT32_C(4096)
#define PSTVNC_CONFIG_AUDIO_CREDIT_FLUSH_ON_EMPTY 1
#define PSTVNC_CONFIG_AUDIO_CREDIT_RETURN_ENABLED 1

#define PSTVNC_CONFIG_AUDIO_PCM_RATE_HZ UINT32_C(48000)
#define PSTVNC_CONFIG_AUDIO_PCM_CHANNELS UINT32_C(2)
#define PSTVNC_CONFIG_AUDIO_PCM_BITS_PER_SAMPLE UINT32_C(16)
#define PSTVNC_CONFIG_AUDIO_PCM_VOLUME_PERCENT UINT32_C(100)

#define PSTVNC_CONFIG_AUDIO_PLAYBACK_BUFFER_CAPACITY UINT32_C(4096)
#define PSTVNC_CONFIG_AUDIO_STARTUP_RESERVOIR_BYTES UINT32_C(458752)
#define PSTVNC_CONFIG_AUDIO_WORKER_PRIORITY 65
#define PSTVNC_CONFIG_AUDIO_WORKER_STACK_BYTES UINT32_C(16384)
#define PSTVNC_CONFIG_AUDIO_RESERVOIR_POLL_US UINT32_C(1000)
#define PSTVNC_CONFIG_AUDIO_CLOCK_POLL_US UINT32_C(1000)

#endif /* PSTVNC_CONFIG_AUDIO_RUNTIME_PROFILE_GENERATED_H */
