/*
 * GENERATED FILE - DO NOT EDIT.
 * Source: src/config/mpeg_runtime_profile.json
 * Generator: scripts/generate-mpeg-runtime-profile.py
 *
 * These are Configuration-selected mechanism values only. They do not create
 * Wire authority, launch a producer, or activate an MPEG generation.
 */

#ifndef PSTVNC_CONFIG_MPEG_RUNTIME_PROFILE_GENERATED_H
#define PSTVNC_CONFIG_MPEG_RUNTIME_PROFILE_GENERATED_H

#include <stdint.h>

#define PSTVNC_CONFIG_MPEG_QUEUE_CAPACITY UINT32_C(524288)
#define PSTVNC_CONFIG_MPEG_INITIAL_CREDIT_BYTES UINT32_C(524288)
#define PSTVNC_CONFIG_MPEG_CREDIT_BATCH_BYTES UINT32_C(8192)
#define PSTVNC_CONFIG_MPEG_CREDIT_FLUSH_ON_EMPTY 1
#define PSTVNC_CONFIG_MPEG_CREDIT_RETURN_ENABLED 1

#define PSTVNC_CONFIG_MPEG_MAX_WIDTH UINT32_C(704)
#define PSTVNC_CONFIG_MPEG_MAX_HEIGHT UINT32_C(480)
#define PSTVNC_CONFIG_MPEG_BYTES_PER_PIXEL UINT32_C(2)
#define PSTVNC_CONFIG_MPEG_FEED_PAYLOAD_CAPACITY UINT32_C(2048)
#define PSTVNC_CONFIG_MPEG_TRANSFER_ALIGNMENT UINT32_C(16)
#define PSTVNC_CONFIG_MPEG_BUFFER_ALIGNMENT UINT32_C(64)

#define PSTVNC_CONFIG_MPEG_WORKER_STACK_BYTES UINT32_C(65536)
#define PSTVNC_CONFIG_MPEG_WORKER_PRIORITY 67
#define PSTVNC_CONFIG_MPEG_JOIN_POLL_DELAY_US UINT32_C(1000)
#define PSTVNC_CONFIG_MPEG_JOIN_POLL_MAX_COUNT UINT32_C(3000)

#define PSTVNC_CONFIG_MPEG_FPS_NUMERATOR UINT32_C(30000)
#define PSTVNC_CONFIG_MPEG_FPS_DENOMINATOR UINT32_C(1001)
#define PSTVNC_CONFIG_MPEG_DROP_ENABLED 0
#define PSTVNC_CONFIG_MPEG_DROP_THRESHOLD_MILLIFRAMES UINT32_C(0)

#endif /* PSTVNC_CONFIG_MPEG_RUNTIME_PROFILE_GENERATED_H */
